apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: fbot
spec:
    replicas: 1
    selector:
        matchLabels:
            app: fbot
    template:
        metadata:
            labels:
                app: fbot
        spec:
            containers:
                - name: fbot
                  image: registry.gitlab.com/z81/fbot:latest
                  env:
                  - name: DISCORD_TOKEN
                    value: Mjc0MjYzMTgxMTkzMzc5ODQw.DyeHpA.1_w3y1mNSCYNQlToezZ98gov8IY